"""Generates src/data/accessories.js.

Reads  tools/accessory-catalogue.json  — categories, names and descriptions
       tools/parts.json                — which products name each part
       tools/product_ids.json          — every product id that exists
Writes src/data/accessories.js

Run parts.py first; it writes the two json files this depends on.

Both scripts assert rather than guess: an accessory pointing at a product id
that products.js no longer defines fails here, instead of shipping a dead link
to the site.
"""
import io, json, os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, 'src', 'data', 'accessories.js')

catalogue = json.load(io.open(os.path.join(HERE, 'accessory-catalogue.json'), encoding='utf-8'))
parts = json.load(io.open(os.path.join(HERE, 'parts.json'), encoding='utf-8'))
known_ids = set(json.load(io.open(os.path.join(HERE, 'product_ids.json'), encoding='utf-8')))
print(f'{len(known_ids)} product ids, {len(parts)} parts named in the catalogue')

categories = catalogue['categories']
cat_order = {c['id']: i for i, c in enumerate(categories)}

# Every part in the extracted index must be described, and every described part
# must still exist in the index — otherwise the two have drifted apart.
named = {a['catalogueName'] for a in catalogue['accessories']}
missing = set(parts) - named
extra = named - set(parts)
assert not missing, f'parts not described in accessory-catalogue.json: {sorted(missing)}'
assert not extra, f'described parts that products.js no longer names: {sorted(extra)}'

rows = []
for a in catalogue['accessories']:
    rec = parts[a['catalogueName']]
    ids = rec['products']                       # ids, in catalogue order, de-duped
    unknown = [i for i in ids if i not in known_ids]
    assert not unknown, f'{a["id"]} links to non-existent product(s): {unknown}'
    assert a['category'] in cat_order, f'{a["id"]} has unknown category {a["category"]}'
    rows.append({**a, 'fits': ids, 'sections': rec['sections'], 'uses': len(ids)})

seen = [r['id'] for r in rows]
dupes = sorted({i for i in seen if seen.count(i) > 1})
assert not dupes, f'duplicate accessory ids: {dupes}'

empty = [c['id'] for c in categories if not any(r['category'] == c['id'] for r in rows)]
assert not empty, f'categories with no parts: {empty}'

# Most-used parts first inside each category — the ones most likely to be wanted.
rows.sort(key=lambda r: (cat_order[r['category']], -r['uses'], r['name']))


def q(s):
    return "'" + s.replace('\\', '\\\\').replace("'", "\\'") + "'"


def arr(xs):
    return '[' + ', '.join(q(x) for x in xs) + ']'


L = ['''/**
 * Accessories and spare parts.
 *
 * NOTHING HERE IS INVENTED. Every entry is a component the V-Tech Aqua 2023
 * catalogue names in the cartridge or bill-of-materials line of a system we
 * list, and `fits` is the set of models that actually name it — derived, not
 * written by hand. Generated by tools/gen_accessories.py; edit that pipeline
 * rather than this file.
 *
 * There are no prices. The catalogue prices complete systems and never prices a
 * part on its own, so every accessory is quoted on request rather than carrying
 * a guessed figure.
 *
 * There are no photographs either — the catalogue does not picture its parts, so
 * cards draw a category glyph instead of a stock image.
 */
import { products, sections } from './products'

export const CATEGORIES = [''']

for c in categories:
    L.append(f"  {{ id: {q(c['id'])}, label: {q(c['label'])}, blurb: {q(c['blurb'])} }},")
L.append(']\n')
L.append('const CATEGORY_LABEL = Object.fromEntries(CATEGORIES.map((c) => [c.id, c.label]))\n')
L.append('''/**
 * `kind` marks these apart from systems so the shared enquiry list can render a
 * part without reaching for a photograph or a product page; `price: null` makes
 * them read as "Price on request" through the same formatter the unpriced
 * catalogue models already use.
 */
const part = (a) => ({
  ...a,
  kind: 'accessory',
  price: null,
  configuration: CATEGORY_LABEL[a.category],
})

export const accessories = [''')

for r in rows:
    L.append('  part({')
    L.append(f"    id: {q(r['id'])},")
    L.append(f"    name: {q(r['name'])},")
    L.append(f"    catalogueName: {q(r['catalogueName'])},")
    L.append(f"    category: {q(r['category'])},")
    if r.get('spec'):
        L.append(f"    spec: {q(r['spec'])},")
    L.append(f"    description: {q(r['description'])},")
    L.append(f"    fits: {arr(r['fits'])},")
    L.append(f"    sections: {arr(r['sections'])},")
    L.append('  }),')

L.append(''']

export const accessoryById = (id) => accessories.find((a) => a.id === id)

export const accessoriesByCategory = (id) =>
  id === 'all' ? accessories : accessories.filter((a) => a.category === id)

/** The catalogue models that list this part, as product objects. */
export const fitsProducts = (a) =>
  (a.fits || []).map((id) => products.find((p) => p.id === id)).filter(Boolean)

/**
 * Which ranges a part belongs to, in catalogue order. A 20-inch jumbo cartridge
 * and a domestic sediment cartridge are both "filter cartridges", so the range
 * is what tells a householder the difference at a glance.
 */
const SHORT = Object.fromEntries(sections.map((s) => [s.id, s.label.split(' ')[0]]))

export const rangeLabels = (a) =>
  sections.filter((s) => (a.sections || []).includes(s.id)).map((s) => SHORT[s.id])

export const RANGES = sections.map((s) => ({ id: s.id, label: SHORT[s.id] }))
''')

io.open(OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(L))
print(f'wrote {OUT}')
print(f'{len(rows)} accessories across {len(categories)} categories')
